export const STARTSIGNUP = 'SIGNUP_STARTS';
export const SUCCESSFULSIGNUP = 'SIGNUP_COMPLETE';
export const FAILEDSIGNUP = 'SIGNUP_ERROR';
export const STARTSIGNIN = 'SIGNIN_STARTS';
export const SUCCESSFULSIGNIN = 'SIGNIN_COMPLETE';
export const FAILEDSIGNIN = 'SIGNIN_ERROR';
